version: '3.8'

services: 
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./.dump:/docker-entrypoint-initdb.d
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_ID: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB_NAME: signal
    ports:
      - 3306:3306

  pma:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - 80:80
    environment:
      PMA_HOST: db